version: "3.1"

services:
  app:
    build: ./app
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:5.7
    hostname: flask-mysql
    environment:
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
      MYSQL_DATABASE: flask_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
